spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

sentry:
  dsn: ${SENTRY_AUTH_TOKEN}
  tracesSampleRate: 1.0
  exception-resolver-order: -2147483647