spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
  output:
    ansi:
      enabled: always
  profiles:
    default: dev

logging:
  level:
    org.springframework.security: TRACE

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
