name: task_manager-check

on:
  - push
  - pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle Wrapper
      run: ./gradlew build
#      working-directory: ./app
 
    - name: Code Coverage
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CDCL_TEST_REPORTER_ID_TASKMANAGER}}
#        JACOCO_SOURCE_PATH: "${{github.workspace}}/app/src/main/java"
        JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
      with:
#        workingDirectory: ./app
        coverageCommand: ./gradlew jacocoTestReport
#        coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
        coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
